# Generated by Django 6.0.3 on 2026-04-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='major',
        ),
    ]
